services:
  - type: web
    name: stockflow-backend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node index.js
    rootDir: backend
    envVars:
      - key: MONGO_URL
        sync: false
      - key: TOKEN_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DASHBOARD_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
